/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bankcard.view;

import com.mycompany.bankcard.config.ImageConfig;
import com.mycompany.bankcard.model.BankCard;
import com.mycompany.bankcard.repository.BankCardManager;
import com.mycompany.bankcard.repository.BankCardRepository;
import java.awt.Component;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.smartcardio.CardException;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;

/**
 *
 * @author admin
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    private BankCardManager bankCardManager;
    private BankCardRepository bankCardRepository;
private final ImageConfig imagePanel = new ImageConfig();
    public Home() {
        initComponents();
        bankCardManager = BankCardManager.getInstance();
        bankCardRepository = new BankCardRepository(bankCardManager);
        imagePanel.setBounds(2, 2, 195, 296);
        panelimage.add(imagePanel);
        setInformation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        panelimage = new javax.swing.JPanel();
        textNumberCard = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textNameCard = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textNumberBalance = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textCreateDate = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textExpirationDate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HOME");
        jLabel1.setToolTipText("");

        btnMenu.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        panelimage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        panelimage.setName(""); // NOI18N

        javax.swing.GroupLayout panelimageLayout = new javax.swing.GroupLayout(panelimage);
        panelimage.setLayout(panelimageLayout);
        panelimageLayout.setHorizontalGroup(
            panelimageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );
        panelimageLayout.setVerticalGroup(
            panelimageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        textNumberCard.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        textNumberCard.setText("001 2001 999");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel3.setText("Number Card");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel4.setText("Name Card");

        textNameCard.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        textNameCard.setText("Pham Nhat Vuong");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel5.setText("Number Balance");

        textNumberBalance.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        textNumberBalance.setText("100.000.000 đ");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel6.setText("Create Date");

        textCreateDate.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        textCreateDate.setText("20/10/2019");

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel7.setText("Expiration Date");

        textExpirationDate.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        textExpirationDate.setText("20/10/2024");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(347, 347, 347)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(panelimage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textNumberCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textNameCard, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(textNumberBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textCreateDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textExpirationDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(136, 136, 136))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)
                        .addComponent(panelimage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(textNumberCard))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(textNameCard))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(textNumberBalance))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(textCreateDate))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(textExpirationDate))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        showMenu(btnMenu);
    }//GEN-LAST:event_btnMenuActionPerformed
    private void showMenu(Component component) {
        JPopupMenu menu = new JPopupMenu();
        JMenuItem menuItemUpdateInfor = new JMenuItem("Update Information");
        menuItemUpdateInfor.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24));
        menuItemUpdateInfor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new Update().setVisible(true);
                setVisible(false);
            }
        });
        JMenuItem menuItemRecharge = new JMenuItem("Recharge Money");
        menuItemRecharge.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24));
        menuItemRecharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new Recharge().setVisible(true);
                setVisible(false);
            }
        });
        JMenuItem menuItemWithdraw = new JMenuItem("Withdraw money");
        menuItemWithdraw.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24));
        menuItemWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new WithdrawMoney().setVisible(true);
                setVisible(false);
            }
        });
        JMenuItem menuItemUpdatePIN = new JMenuItem("Update PIN");
        menuItemUpdatePIN.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24));
        menuItemUpdatePIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new UpdatePIN().setVisible(true);
                setVisible(false);
            }
        });
        JMenuItem menuItemHistory = new JMenuItem("History");
        menuItemHistory.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24));
        menuItemHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new History().setVisible(true);
                setVisible(false);
            }
        });
        JMenuItem menuItemExit = new JMenuItem("Exit");
        menuItemExit.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24));
        menuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    bankCardManager.disconnect();
                    new Login().setVisible(true);
                    setVisible(false);
                } catch (NullPointerException ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                } catch (CardException ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        menu.add(menuItemUpdateInfor);
        menu.add(menuItemRecharge);
        menu.add(menuItemWithdraw);
        menu.add(menuItemUpdatePIN);
        menu.add(menuItemHistory);
        menu.add(menuItemExit);
        menu.show(component, 0, -component.getHeight());
    }

    /**
     * @param args the command line arguments
     */
    private void setInformation() {
        BankCard bankCard = getInformation();
        System.out.println(bankCard.toString());
        if (bankCard == null) {
            JOptionPane.showMessageDialog(this, "Error! An error occurred. Please try again later.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        textNumberCard.setText(bankCard.getNumberCard());
        textNameCard.setText(bankCard.getNameCard());
        textNumberBalance.setText(String.format("%,d", bankCard.getNumberBalance()) + " VND");
        textCreateDate.setText(dateFormat.format(bankCard.getCreateDate()));
        textExpirationDate.setText(dateFormat.format(bankCard.getExpirationDate()));
        Image avatar = getImage(bankCard.getImageAvatar());
        imagePanel.setImage(avatar);
    }

    public BankCard getInformation() {
        return bankCardRepository.getInformationCard();
    }
    public Image getImage(byte[] data) {
        return new ImageIcon(data).getImage();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel panelimage;
    private javax.swing.JLabel textCreateDate;
    private javax.swing.JLabel textExpirationDate;
    private javax.swing.JLabel textNameCard;
    private javax.swing.JLabel textNumberBalance;
    private javax.swing.JLabel textNumberCard;
    // End of variables declaration//GEN-END:variables
}
