/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bankcard.view;

import com.mycompany.bankcard.repository.BankCardManager;
import com.mycompany.bankcard.repository.BankCardRepository;
import static com.mycompany.bankcard.util.Constans.CARD_HAS_BLOCKED;
import javax.smartcardio.CardException;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class UpdatePIN extends javax.swing.JFrame {

    private BankCardRepository bankCardRepository;
    private BankCardManager bankCardManager;

    /**
     * Creates new form UpdatePIN
     */
    public UpdatePIN() {
        initComponents();
        bankCardManager = BankCardManager.getInstance();
        bankCardRepository = new BankCardRepository(bankCardManager);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pinCodeCurrent = new javax.swing.JPasswordField();
        btnUpdatePin = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        pinCodeNew = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        pinCodeConfirm = new javax.swing.JPasswordField();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("UPDATE PIN CODE");
        jLabel1.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel4.setText("Input PIN current");

        pinCodeCurrent.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        pinCodeCurrent.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnUpdatePin.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        btnUpdatePin.setText("Enter");
        btnUpdatePin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePinActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel5.setText("Input PIN new");

        pinCodeNew.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        pinCodeNew.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel6.setText("Input PIN confirm");

        pinCodeConfirm.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        pinCodeConfirm.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnBack.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(27, 27, 27)
                                .addComponent(pinCodeConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(27, 27, 27)
                                .addComponent(pinCodeNew, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(pinCodeCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(btnUpdatePin, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pinCodeCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pinCodeNew, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pinCodeConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdatePin, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new Home().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdatePinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePinActionPerformed
        updatePIN();
    }//GEN-LAST:event_btnUpdatePinActionPerformed
    private void updatePIN() {
        String pinCurrent = new String(pinCodeCurrent.getPassword());
        String pinNew = new String(pinCodeNew.getPassword());
        String pinConfirm = new String(pinCodeConfirm.getPassword());
        String errorMessage = updatePIN(pinCurrent, pinNew, pinConfirm);

        if (errorMessage != null) {
            JOptionPane.showMessageDialog(this, errorMessage, "Error", JOptionPane.ERROR_MESSAGE);
            if (errorMessage.equals(CARD_HAS_BLOCKED)) {
                new Login().setVisible(true);
                setVisible(false);
            }
            return;
        }

        JOptionPane.showMessageDialog(this, "Update PIN successful!", "Notification", JOptionPane.INFORMATION_MESSAGE);
//        new HomePanel().setVisible(true);
//        setVisible(false);
    }

    public String updatePIN(String currentPin, String newPin, String confirmNewPin) {
        String errorMessage = validate(currentPin, newPin, confirmNewPin);

        if (errorMessage != null) {
            return errorMessage;
        }

        try {
            Integer retriesRemaining = bankCardRepository.updatePin(currentPin, newPin);

            if (retriesRemaining == null) {
                return null;
            }

            if (retriesRemaining == 0) {
                disconnect();
                return CARD_HAS_BLOCKED;
            }

            return "Your current PIN is incorrect!";
        } catch (CardException e) {
            return "Faild\n. Please try again later.";
        }
    }

    private String validate(String currentPin, String newPin, String confirmNewPin) {
        if (currentPin == null || currentPin.isBlank()) {
            return "Enter your current PIN.";
        }

        if (newPin == null || newPin.isBlank()) {
            return "Enter your new PIN.";
        }

        if (newPin.length() != 6) {
            return "New PIN is invalid!";
        }

        if (confirmNewPin == null || confirmNewPin.isBlank()) {
            return "Enter your confirm new PIN.";
        }

        if (confirmNewPin.equals(newPin)) {
            return null;
        }

        return "Confirm new PIN is not match!";
    }

    private void disconnect() {
        try {
            bankCardManager.disconnect();
        } catch (CardException e) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdatePin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField pinCodeConfirm;
    private javax.swing.JPasswordField pinCodeCurrent;
    private javax.swing.JPasswordField pinCodeNew;
    // End of variables declaration//GEN-END:variables
}
